<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Client__CLASSMETADATA__' => 0,
'App__Entity__DemandeDevis__CLASSMETADATA__' => 1,
'App__Entity__DemandePrestation__CLASSMETADATA__' => 2,
'App__Entity__Local__CLASSMETADATA__' => 3,
'App__Entity__Prestation__CLASSMETADATA__' => 4,
'App__Entity__Prix__CLASSMETADATA__' => 5,
'App__Entity__User__CLASSMETADATA__' => 6,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Client',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ClientRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'prenom' => $o[3],
                    'email' => $o[4],
                    'telephone' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'email' => 'email',
                    'telephone' => 'telephone',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'email' => 'email',
                    'telephone' => 'telephone',
                ],
            ],
            'table' => [
                [
                    'name' => 'client',
                ],
            ],
            'associationMappings' => [
                [
                    'demandeDevis' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[7],
            ],
            'name' => [
                'App\\Entity\\Client',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'prenom',
                'email',
                'telephone',
            ],
            'columnName' => [
                1 => 'id',
                'nom',
                'prenom',
                'email',
                'telephone',
            ],
            'length' => [
                2 => 255,
                255,
                255,
                255,
            ],
            'nullable' => [
                4 => true,
            ],
            'fetch' => [
                6 => 2,
            ],
            'sourceEntity' => [
                6 => 'App\\Entity\\Client',
            ],
            'mappedBy' => [
                6 => 'client',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                6 => 'demandeDevis',
            ],
            'targetEntity' => [
                6 => 'App\\Entity\\DemandeDevis',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\OneToOneInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneInverseSideMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\DemandeDevis',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\DemandeDevisRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'creneau_horaire' => $o[2],
                    'date_demande' => $o[3],
                    'date_creation' => $o[4],
                    'frequence' => $o[5],
                    'statut' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'creneau_horaire' => 'creneau_horaire',
                    'date_demande' => 'date_demande',
                    'date_creation' => 'date_creation',
                    'frequence' => 'frequence',
                    'statut' => 'statut',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'creneau_horaire' => 'creneau_horaire',
                    'date_demande' => 'date_demande',
                    'date_creation' => 'date_creation',
                    'frequence' => 'frequence',
                    'statut' => 'statut',
                ],
            ],
            'table' => [
                [
                    'name' => 'demande_devis',
                ],
            ],
            'associationMappings' => [
                [
                    'client' => $o[7],
                    'local' => $o[9],
                    'demandePrestations' => $o[11],
                    'prix' => $o[12],
                ],
            ],
            'idGenerator' => [
                $o[13],
            ],
            'name' => [
                'App\\Entity\\DemandeDevis',
                8 => 'client_id',
                10 => 'local_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'date',
                'datetime',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'creneau_horaire',
                'date_demande',
                'date_creation',
                'frequence',
                'statut',
            ],
            'columnName' => [
                1 => 'id',
                'creneau_horaire',
                'date_demande',
                'date_creation',
                'frequence',
                'statut',
            ],
            'length' => [
                2 => 255,
                5 => 255,
                255,
            ],
            'fetch' => [
                7 => 2,
                9 => 2,
                11 => 2,
                2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\DemandeDevis',
                9 => 'App\\Entity\\DemandeDevis',
                11 => 'App\\Entity\\DemandeDevis',
                'App\\Entity\\DemandeDevis',
            ],
            'inversedBy' => [
                7 => 'demandeDevis',
                9 => 'demandeDevis',
            ],
            'sourceToTargetKeyColumns' => [
                7 => [
                    'client_id' => 'id',
                ],
                9 => [
                    'local_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                7 => [
                    'id' => 'client_id',
                ],
                9 => [
                    'id' => 'local_id',
                ],
            ],
            'joinColumns' => [
                7 => [
                    $o[8],
                ],
                9 => [
                    $o[10],
                ],
            ],
            'joinColumnFieldNames' => [
                7 => [
                    'client_id' => 'client_id',
                ],
                9 => [
                    'local_id' => 'local_id',
                ],
            ],
            'nullable' => [
                8 => true,
                10 => true,
            ],
            'referencedColumnName' => [
                8 => 'id',
                10 => 'id',
            ],
            'mappedBy' => [
                11 => 'Demande_devis',
                'demande_devis',
            ],
            'cascade' => [
                12 => [
                    'persist',
                    'remove',
                ],
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'client',
                9 => 'local',
                11 => 'demandePrestations',
                'prix',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\Client',
                9 => 'App\\Entity\\Local',
                11 => 'App\\Entity\\DemandePrestation',
                'App\\Entity\\Prix',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\DemandePrestation',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\DemandePrestationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'details_specifiques' => $o[2],
                    'admin_description' => $o[3],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'details_specifiques' => 'details_specifiques',
                    'admin_description' => 'admin_description',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'details_specifiques' => 'details_specifiques',
                    'admin_description' => 'admin_description',
                ],
            ],
            'table' => [
                [
                    'name' => 'demande_prestation',
                ],
            ],
            'associationMappings' => [
                [
                    'Demande_devis' => $o[4],
                    'prestation' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\DemandePrestation',
                5 => 'demande_devis_id',
                7 => 'prestation_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
            ],
            'fieldName' => [
                1 => 'id',
                'details_specifiques',
                'admin_description',
            ],
            'columnName' => [
                1 => 'id',
                'details_specifiques',
                'admin_description',
            ],
            'length' => [
                2 => 255,
            ],
            'nullable' => [
                2 => true,
                true,
                5 => true,
                7 => true,
            ],
            'fetch' => [
                4 => 2,
                6 => 2,
            ],
            'sourceEntity' => [
                4 => 'App\\Entity\\DemandePrestation',
                6 => 'App\\Entity\\DemandePrestation',
            ],
            'inversedBy' => [
                4 => 'demandePrestations',
                6 => 'demandePrestations',
            ],
            'sourceToTargetKeyColumns' => [
                4 => [
                    'demande_devis_id' => 'id',
                ],
                6 => [
                    'prestation_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                4 => [
                    'id' => 'demande_devis_id',
                ],
                6 => [
                    'id' => 'prestation_id',
                ],
            ],
            'joinColumns' => [
                4 => [
                    $o[5],
                ],
                6 => [
                    $o[7],
                ],
            ],
            'joinColumnFieldNames' => [
                4 => [
                    'demande_devis_id' => 'demande_devis_id',
                ],
                6 => [
                    'prestation_id' => 'prestation_id',
                ],
            ],
            'referencedColumnName' => [
                5 => 'id',
                7 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                4 => 'Demande_devis',
                6 => 'prestation',
            ],
            'targetEntity' => [
                4 => 'App\\Entity\\DemandeDevis',
                6 => 'App\\Entity\\Prestation',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Local',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\LocalRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'type_local' => $o[2],
                    'ville' => $o[3],
                    'surface_m2' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'type_local' => 'type_local',
                    'ville' => 'ville',
                    'surface_m2' => 'surface_m2',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'type_local' => 'type_local',
                    'ville' => 'ville',
                    'surface_m2' => 'surface_m2',
                ],
            ],
            'table' => [
                [
                    'name' => 'local',
                ],
            ],
            'associationMappings' => [
                [
                    'demandeDevis' => $o[5],
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\Local',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'integer',
            ],
            'fieldName' => [
                1 => 'id',
                'type_local',
                'ville',
                'surface_m2',
            ],
            'columnName' => [
                1 => 'id',
                'type_local',
                'ville',
                'surface_m2',
            ],
            'length' => [
                2 => 255,
                255,
            ],
            'fetch' => [
                5 => 2,
            ],
            'sourceEntity' => [
                5 => 'App\\Entity\\Local',
            ],
            'mappedBy' => [
                5 => 'local',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                5 => 'demandeDevis',
            ],
            'targetEntity' => [
                5 => 'App\\Entity\\DemandeDevis',
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Prestation',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\PrestationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'code_prestation' => $o[2],
                    'libelle' => $o[3],
                    'description' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'code_prestation' => 'code_prestation',
                    'libelle' => 'libelle',
                    'description' => 'description',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'code_prestation' => 'code_prestation',
                    'libelle' => 'libelle',
                    'description' => 'description',
                ],
            ],
            'table' => [
                [
                    'name' => 'prestation',
                ],
            ],
            'associationMappings' => [
                [
                    'demandePrestations' => $o[5],
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\Prestation',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'text',
            ],
            'fieldName' => [
                1 => 'id',
                'code_prestation',
                'libelle',
                'description',
            ],
            'columnName' => [
                1 => 'id',
                'code_prestation',
                'libelle',
                'description',
            ],
            'length' => [
                2 => 255,
                255,
            ],
            'nullable' => [
                4 => true,
            ],
            'fetch' => [
                5 => 2,
            ],
            'sourceEntity' => [
                5 => 'App\\Entity\\Prestation',
            ],
            'mappedBy' => [
                5 => 'prestation',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                5 => 'demandePrestations',
            ],
            'targetEntity' => [
                5 => 'App\\Entity\\DemandePrestation',
            ],
        ],
    ],
    $o[0],
    []
); } },
5 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Prix',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\PrixRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'montant_ht' => $o[2],
                    'remise' => $o[3],
                    'tva' => $o[4],
                    'total_ttc' => $o[5],
                    'date_creation' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'montant_ht' => 'montant_ht',
                    'remise' => 'remise',
                    'tva' => 'tva',
                    'total_ttc' => 'total_ttc',
                    'date_creation' => 'date_creation',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'montant_ht' => 'montant_ht',
                    'remise' => 'remise',
                    'tva' => 'tva',
                    'total_ttc' => 'total_ttc',
                    'date_creation' => 'date_creation',
                ],
            ],
            'table' => [
                [
                    'name' => 'prix',
                ],
            ],
            'associationMappings' => [
                [
                    'demande_devis' => $o[7],
                ],
            ],
            'idGenerator' => [
                $o[9],
            ],
            'name' => [
                'App\\Entity\\Prix',
                8 => 'demande_devis_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'decimal',
                'decimal',
                'decimal',
                'decimal',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'montant_ht',
                'remise',
                'tva',
                'total_ttc',
                'date_creation',
            ],
            'columnName' => [
                1 => 'id',
                'montant_ht',
                'remise',
                'tva',
                'total_ttc',
                'date_creation',
            ],
            'precision' => [
                2 => 10,
                10,
                5,
                10,
            ],
            'scale' => [
                2 => 2,
                2,
                2,
                2,
            ],
            'nullable' => [
                3 => true,
                6 => true,
                8 => false,
            ],
            'cascade' => [
                7 => [
                    'persist',
                ],
            ],
            'fetch' => [
                7 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Prix',
            ],
            'inversedBy' => [
                7 => 'prix',
            ],
            'sourceToTargetKeyColumns' => [
                7 => [
                    'demande_devis_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                7 => [
                    'id' => 'demande_devis_id',
                ],
            ],
            'joinColumns' => [
                7 => [
                    $o[8],
                ],
            ],
            'joinColumnFieldNames' => [
                7 => [
                    'demande_devis_id' => 'demande_devis_id',
                ],
            ],
            'deferrable' => [
                8 => false,
            ],
            'unique' => [
                8 => true,
            ],
            'referencedColumnName' => [
                8 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'demande_devis',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\DemandeDevis',
            ],
        ],
    ],
    $o[0],
    []
); } },
6 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\User',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UserRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'email' => $o[2],
                    'roles' => $o[3],
                    'password' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                ],
            ],
            'table' => [
                [
                    'name' => 'user',
                    'uniqueConstraints' => [
                        'UNIQ_IDENTIFIER_EMAIL' => [
                            'fields' => [
                                'email',
                            ],
                        ],
                    ],
                ],
            ],
            'idGenerator' => [
                $o[5],
            ],
            'name' => [
                'App\\Entity\\User',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'json',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
            ],
            'columnName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
            ],
            'length' => [
                2 => 180,
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
