<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9_K60C_Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.9.k60C.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'prestation' => ['privates', '.errored..service_locator.9.k60C..App\\Entity\\Prestation', NULL, 'Cannot autowire service ".service_locator.9.k60C.": it needs an instance of "App\\Entity\\Prestation" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'prestation' => 'App\\Entity\\Prestation',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.9.k60C.'])) {
            return $container->privates['.service_locator.9.k60C.'];
        }

        return $container->privates['.service_locator.9.k60C.'] = $instance;
    }
}
