<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8qx4UPgService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.8qx4UPg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'local' => ['privates', '.errored..service_locator.8qx4UPg.App\\Entity\\Local', NULL, 'Cannot autowire service ".service_locator.8qx4UPg": it needs an instance of "App\\Entity\\Local" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'local' => 'App\\Entity\\Local',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.8qx4UPg'])) {
            return $container->privates['.service_locator.8qx4UPg'];
        }

        return $container->privates['.service_locator.8qx4UPg'] = $instance;
    }
}
