<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ClientController::index' => ['privates', '.service_locator.DbhFNW6.App\\Controller\\ClientController::index()', 'getClientControllerindexService', true],
            'App\\Controller\\ClientController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\ClientController::new()', 'getClientControllernewService', true],
            'App\\Controller\\ClientController::show' => ['privates', '.service_locator.5eYkN6Y.App\\Controller\\ClientController::show()', 'getClientControllershowService', true],
            'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.XgV966x.App\\Controller\\ClientController::edit()', 'getClientControllereditService', true],
            'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.XgV966x.App\\Controller\\ClientController::delete()', 'getClientControllerdeleteService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.YkXyj0o.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\DemandeDevisController::liste' => ['privates', '.service_locator.gm.pLUF.App\\Controller\\DemandeDevisController::liste()', 'getDemandeDevisControllerlisteService', true],
            'App\\Controller\\DemandeDevisController::index' => ['privates', '.service_locator.mS.j._d.App\\Controller\\DemandeDevisController::index()', 'getDemandeDevisControllerindexService', true],
            'App\\Controller\\DemandeDevisController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\DemandeDevisController::new()', 'getDemandeDevisControllernewService', true],
            'App\\Controller\\DemandeDevisController::show' => ['privates', '.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::show()', 'getDemandeDevisControllershowService', true],
            'App\\Controller\\DemandeDevisController::edit' => ['privates', '.service_locator.e9Bfsdw.App\\Controller\\DemandeDevisController::edit()', 'getDemandeDevisControllereditService', true],
            'App\\Controller\\DemandeDevisController::delete' => ['privates', '.service_locator.BC6D9_k.App\\Controller\\DemandeDevisController::delete()', 'getDemandeDevisControllerdeleteService', true],
            'App\\Controller\\DemandeDevisController::downloadPdf' => ['privates', '.service_locator.xn93gmd.App\\Controller\\DemandeDevisController::downloadPdf()', 'getDemandeDevisControllerdownloadPdfService', true],
            'App\\Controller\\DemandeDevisController::sendEmail' => ['privates', '.service_locator.g0Xcbzl.App\\Controller\\DemandeDevisController::sendEmail()', 'getDemandeDevisControllersendEmailService', true],
            'App\\Controller\\DemandeDevisController::valider' => ['privates', '.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::valider()', 'getDemandeDevisControllervaliderService', true],
            'App\\Controller\\DemandeDevisController::updatePrestations' => ['privates', '.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::updatePrestations()', 'getDemandeDevisControllerupdatePrestationsService', true],
            'App\\Controller\\LocalController::index' => ['privates', '.service_locator.bGytb4Y.App\\Controller\\LocalController::index()', 'getLocalControllerindexService', true],
            'App\\Controller\\LocalController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\LocalController::new()', 'getLocalControllernewService', true],
            'App\\Controller\\LocalController::show' => ['privates', '.service_locator.wt..67W.App\\Controller\\LocalController::show()', 'getLocalControllershowService', true],
            'App\\Controller\\LocalController::edit' => ['privates', '.service_locator.8qx4UPg.App\\Controller\\LocalController::edit()', 'getLocalControllereditService', true],
            'App\\Controller\\LocalController::delete' => ['privates', '.service_locator.8qx4UPg.App\\Controller\\LocalController::delete()', 'getLocalControllerdeleteService', true],
            'App\\Controller\\PrestationController::index' => ['privates', '.service_locator.cXCrH8j.App\\Controller\\PrestationController::index()', 'getPrestationControllerindexService', true],
            'App\\Controller\\PrestationController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\PrestationController::new()', 'getPrestationControllernewService', true],
            'App\\Controller\\PrestationController::show' => ['privates', '.service_locator.7bEyMfQ.App\\Controller\\PrestationController::show()', 'getPrestationControllershowService', true],
            'App\\Controller\\PrestationController::edit' => ['privates', '.service_locator.9.k60C..App\\Controller\\PrestationController::edit()', 'getPrestationControllereditService', true],
            'App\\Controller\\PrestationController::delete' => ['privates', '.service_locator.9.k60C..App\\Controller\\PrestationController::delete()', 'getPrestationControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\SecurityController::register()', 'getSecurityControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ClientController:index' => ['privates', '.service_locator.DbhFNW6.App\\Controller\\ClientController::index()', 'getClientControllerindexService', true],
            'App\\Controller\\ClientController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\ClientController::new()', 'getClientControllernewService', true],
            'App\\Controller\\ClientController:show' => ['privates', '.service_locator.5eYkN6Y.App\\Controller\\ClientController::show()', 'getClientControllershowService', true],
            'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.XgV966x.App\\Controller\\ClientController::edit()', 'getClientControllereditService', true],
            'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.XgV966x.App\\Controller\\ClientController::delete()', 'getClientControllerdeleteService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.YkXyj0o.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\DemandeDevisController:liste' => ['privates', '.service_locator.gm.pLUF.App\\Controller\\DemandeDevisController::liste()', 'getDemandeDevisControllerlisteService', true],
            'App\\Controller\\DemandeDevisController:index' => ['privates', '.service_locator.mS.j._d.App\\Controller\\DemandeDevisController::index()', 'getDemandeDevisControllerindexService', true],
            'App\\Controller\\DemandeDevisController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\DemandeDevisController::new()', 'getDemandeDevisControllernewService', true],
            'App\\Controller\\DemandeDevisController:show' => ['privates', '.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::show()', 'getDemandeDevisControllershowService', true],
            'App\\Controller\\DemandeDevisController:edit' => ['privates', '.service_locator.e9Bfsdw.App\\Controller\\DemandeDevisController::edit()', 'getDemandeDevisControllereditService', true],
            'App\\Controller\\DemandeDevisController:delete' => ['privates', '.service_locator.BC6D9_k.App\\Controller\\DemandeDevisController::delete()', 'getDemandeDevisControllerdeleteService', true],
            'App\\Controller\\DemandeDevisController:downloadPdf' => ['privates', '.service_locator.xn93gmd.App\\Controller\\DemandeDevisController::downloadPdf()', 'getDemandeDevisControllerdownloadPdfService', true],
            'App\\Controller\\DemandeDevisController:sendEmail' => ['privates', '.service_locator.g0Xcbzl.App\\Controller\\DemandeDevisController::sendEmail()', 'getDemandeDevisControllersendEmailService', true],
            'App\\Controller\\DemandeDevisController:valider' => ['privates', '.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::valider()', 'getDemandeDevisControllervaliderService', true],
            'App\\Controller\\DemandeDevisController:updatePrestations' => ['privates', '.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::updatePrestations()', 'getDemandeDevisControllerupdatePrestationsService', true],
            'App\\Controller\\LocalController:index' => ['privates', '.service_locator.bGytb4Y.App\\Controller\\LocalController::index()', 'getLocalControllerindexService', true],
            'App\\Controller\\LocalController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\LocalController::new()', 'getLocalControllernewService', true],
            'App\\Controller\\LocalController:show' => ['privates', '.service_locator.wt..67W.App\\Controller\\LocalController::show()', 'getLocalControllershowService', true],
            'App\\Controller\\LocalController:edit' => ['privates', '.service_locator.8qx4UPg.App\\Controller\\LocalController::edit()', 'getLocalControllereditService', true],
            'App\\Controller\\LocalController:delete' => ['privates', '.service_locator.8qx4UPg.App\\Controller\\LocalController::delete()', 'getLocalControllerdeleteService', true],
            'App\\Controller\\PrestationController:index' => ['privates', '.service_locator.cXCrH8j.App\\Controller\\PrestationController::index()', 'getPrestationControllerindexService', true],
            'App\\Controller\\PrestationController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\PrestationController::new()', 'getPrestationControllernewService', true],
            'App\\Controller\\PrestationController:show' => ['privates', '.service_locator.7bEyMfQ.App\\Controller\\PrestationController::show()', 'getPrestationControllershowService', true],
            'App\\Controller\\PrestationController:edit' => ['privates', '.service_locator.9.k60C..App\\Controller\\PrestationController::edit()', 'getPrestationControllereditService', true],
            'App\\Controller\\PrestationController:delete' => ['privates', '.service_locator.9.k60C..App\\Controller\\PrestationController::delete()', 'getPrestationControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\SecurityController::register()', 'getSecurityControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ClientController::index' => '?',
            'App\\Controller\\ClientController::new' => '?',
            'App\\Controller\\ClientController::show' => '?',
            'App\\Controller\\ClientController::edit' => '?',
            'App\\Controller\\ClientController::delete' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\DemandeDevisController::liste' => '?',
            'App\\Controller\\DemandeDevisController::index' => '?',
            'App\\Controller\\DemandeDevisController::new' => '?',
            'App\\Controller\\DemandeDevisController::show' => '?',
            'App\\Controller\\DemandeDevisController::edit' => '?',
            'App\\Controller\\DemandeDevisController::delete' => '?',
            'App\\Controller\\DemandeDevisController::downloadPdf' => '?',
            'App\\Controller\\DemandeDevisController::sendEmail' => '?',
            'App\\Controller\\DemandeDevisController::valider' => '?',
            'App\\Controller\\DemandeDevisController::updatePrestations' => '?',
            'App\\Controller\\LocalController::index' => '?',
            'App\\Controller\\LocalController::new' => '?',
            'App\\Controller\\LocalController::show' => '?',
            'App\\Controller\\LocalController::edit' => '?',
            'App\\Controller\\LocalController::delete' => '?',
            'App\\Controller\\PrestationController::index' => '?',
            'App\\Controller\\PrestationController::new' => '?',
            'App\\Controller\\PrestationController::show' => '?',
            'App\\Controller\\PrestationController::edit' => '?',
            'App\\Controller\\PrestationController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ClientController:index' => '?',
            'App\\Controller\\ClientController:new' => '?',
            'App\\Controller\\ClientController:show' => '?',
            'App\\Controller\\ClientController:edit' => '?',
            'App\\Controller\\ClientController:delete' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\DemandeDevisController:liste' => '?',
            'App\\Controller\\DemandeDevisController:index' => '?',
            'App\\Controller\\DemandeDevisController:new' => '?',
            'App\\Controller\\DemandeDevisController:show' => '?',
            'App\\Controller\\DemandeDevisController:edit' => '?',
            'App\\Controller\\DemandeDevisController:delete' => '?',
            'App\\Controller\\DemandeDevisController:downloadPdf' => '?',
            'App\\Controller\\DemandeDevisController:sendEmail' => '?',
            'App\\Controller\\DemandeDevisController:valider' => '?',
            'App\\Controller\\DemandeDevisController:updatePrestations' => '?',
            'App\\Controller\\LocalController:index' => '?',
            'App\\Controller\\LocalController:new' => '?',
            'App\\Controller\\LocalController:show' => '?',
            'App\\Controller\\LocalController:edit' => '?',
            'App\\Controller\\LocalController:delete' => '?',
            'App\\Controller\\PrestationController:index' => '?',
            'App\\Controller\\PrestationController:new' => '?',
            'App\\Controller\\PrestationController:show' => '?',
            'App\\Controller\\PrestationController:edit' => '?',
            'App\\Controller\\PrestationController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
        ]));

        if (isset($container->privates['argument_resolver.service'])) {
            return $container->privates['argument_resolver.service'];
        }

        return $container->privates['argument_resolver.service'] = $instance;
    }
}
