<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevisServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\DemandeDevisService' shared autowired service.
     *
     * @return \App\Service\DemandeDevisService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\DemandeDevisService'])) {
            return $container->privates['App\\Service\\DemandeDevisService'];
        }

        $instance = new \App\Service\DemandeDevisService($a);

        if (isset($container->privates['App\\Service\\DemandeDevisService'])) {
            return $container->privates['App\\Service\\DemandeDevisService'];
        }

        return $container->privates['App\\Service\\DemandeDevisService'] = $instance;
    }
}
