<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevisControllerlisteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.gm.pLUF.App\Controller\DemandeDevisController::liste()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gm.pLUF.App\\Controller\\DemandeDevisController::liste()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\DemandeDevisRepository', 'getDemandeDevisRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\DemandeDevisRepository',
        ]))->withContext('App\\Controller\\DemandeDevisController::liste()', $container);
    }
}
