<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevisControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.mS.j._d.App\Controller\DemandeDevisController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeDevisService' => ['privates', 'App\\Service\\DemandeDevisService', 'getDemandeDevisServiceService', true],
        ], [
            'demandeDevisService' => 'App\\Service\\DemandeDevisService',
        ]))->withContext('App\\Controller\\DemandeDevisController::index()', $container);

        if (isset($container->privates['.service_locator.mS.j._d.App\\Controller\\DemandeDevisController::index()'])) {
            return $container->privates['.service_locator.mS.j._d.App\\Controller\\DemandeDevisController::index()'];
        }

        return $container->privates['.service_locator.mS.j._d.App\\Controller\\DemandeDevisController::index()'] = $instance;
    }
}
