<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevis5Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.xn93gmd.App\Entity\DemandeDevis' shared service.
     *
     * @return \App\Entity\DemandeDevis
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xn93gmd": it needs an instance of "App\\Entity\\DemandeDevis" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
