<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevisControllerdeleteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.BC6D9_k.App\Controller\DemandeDevisController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeDevi' => ['privates', '.errored..service_locator.BC6D9_k.App\\Entity\\DemandeDevis', NULL, 'Cannot autowire service ".service_locator.BC6D9_k": it needs an instance of "App\\Entity\\DemandeDevis" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'demandeDevi' => 'App\\Entity\\DemandeDevis',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\DemandeDevisController::delete()', $container);

        if (isset($container->privates['.service_locator.BC6D9_k.App\\Controller\\DemandeDevisController::delete()'])) {
            return $container->privates['.service_locator.BC6D9_k.App\\Controller\\DemandeDevisController::delete()'];
        }

        return $container->privates['.service_locator.BC6D9_k.App\\Controller\\DemandeDevisController::delete()'] = $instance;
    }
}
