<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevisControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.e9Bfsdw.App\Controller\DemandeDevisController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeDevi' => ['privates', '.errored..service_locator.e9Bfsdw.App\\Entity\\DemandeDevis', NULL, 'Cannot autowire service ".service_locator.e9Bfsdw": it needs an instance of "App\\Entity\\DemandeDevis" but this type has been excluded because it\'s a Doctrine entity.'],
            'demandeDevisService' => ['privates', 'App\\Service\\DemandeDevisService', 'getDemandeDevisServiceService', true],
        ], [
            'demandeDevi' => 'App\\Entity\\DemandeDevis',
            'demandeDevisService' => 'App\\Service\\DemandeDevisService',
        ]))->withContext('App\\Controller\\DemandeDevisController::edit()', $container);

        if (isset($container->privates['.service_locator.e9Bfsdw.App\\Controller\\DemandeDevisController::edit()'])) {
            return $container->privates['.service_locator.e9Bfsdw.App\\Controller\\DemandeDevisController::edit()'];
        }

        return $container->privates['.service_locator.e9Bfsdw.App\\Controller\\DemandeDevisController::edit()'] = $instance;
    }
}
