<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevisControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DemandeDevisController' shared autowired service.
     *
     * @return \App\Controller\DemandeDevisController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DemandeDevisController'] = $instance = new \App\Controller\DemandeDevisController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\DemandeDevisController', $container));

        return $instance;
    }
}
