<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevisControllersendEmailService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.g0Xcbzl.App\Controller\DemandeDevisController::sendEmail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeDevis' => ['privates', '.errored..service_locator.g0Xcbzl.App\\Entity\\DemandeDevis', NULL, 'Cannot autowire service ".service_locator.g0Xcbzl": it needs an instance of "App\\Entity\\DemandeDevis" but this type has been excluded because it\'s a Doctrine entity.'],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
        ], [
            'demandeDevis' => 'App\\Entity\\DemandeDevis',
            'emailService' => 'App\\Service\\EmailService',
        ]))->withContext('App\\Controller\\DemandeDevisController::sendEmail()', $container);

        if (isset($container->privates['.service_locator.g0Xcbzl.App\\Controller\\DemandeDevisController::sendEmail()'])) {
            return $container->privates['.service_locator.g0Xcbzl.App\\Controller\\DemandeDevisController::sendEmail()'];
        }

        return $container->privates['.service_locator.g0Xcbzl.App\\Controller\\DemandeDevisController::sendEmail()'] = $instance;
    }
}
