<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevisControllershowService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.5KuoRPf.App\Controller\DemandeDevisController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.5KuoRPf'] ?? $container->load('get_ServiceLocator_5KuoRPfService'));

        if (isset($container->privates['.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::show()'])) {
            return $container->privates['.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::show()'];
        }

        $instance = $a->withContext('App\\Controller\\DemandeDevisController::show()', $container);

        if (isset($container->privates['.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::show()'])) {
            return $container->privates['.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::show()'];
        }

        return $container->privates['.service_locator.5KuoRPf.App\\Controller\\DemandeDevisController::show()'] = $instance;
    }
}
