<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevisControllerdownloadPdfService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xn93gmd.App\Controller\DemandeDevisController::downloadPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeDevis' => ['privates', '.errored..service_locator.xn93gmd.App\\Entity\\DemandeDevis', NULL, 'Cannot autowire service ".service_locator.xn93gmd": it needs an instance of "App\\Entity\\DemandeDevis" but this type has been excluded because it\'s a Doctrine entity.'],
            'pdfGenerator' => ['privates', 'App\\Service\\PdfGenerator', 'getPdfGeneratorService', true],
        ], [
            'demandeDevis' => 'App\\Entity\\DemandeDevis',
            'pdfGenerator' => 'App\\Service\\PdfGenerator',
        ]))->withContext('App\\Controller\\DemandeDevisController::downloadPdf()', $container);

        if (isset($container->privates['.service_locator.xn93gmd.App\\Controller\\DemandeDevisController::downloadPdf()'])) {
            return $container->privates['.service_locator.xn93gmd.App\\Controller\\DemandeDevisController::downloadPdf()'];
        }

        return $container->privates['.service_locator.xn93gmd.App\\Controller\\DemandeDevisController::downloadPdf()'] = $instance;
    }
}
