<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.YkXyj0o.App\Controller\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YkXyj0o.App\\Controller\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeDevisRepository' => ['privates', 'App\\Repository\\DemandeDevisRepository', 'getDemandeDevisRepositoryService', true],
        ], [
            'demandeDevisRepository' => 'App\\Repository\\DemandeDevisRepository',
        ]))->withContext('App\\Controller\\DashboardController::index()', $container);
    }
}
