<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.bGytb4Y.App\Controller\LocalController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bGytb4Y.App\\Controller\\LocalController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'localRepository' => ['privates', 'App\\Repository\\LocalRepository', 'getLocalRepositoryService', true],
        ], [
            'localRepository' => 'App\\Repository\\LocalRepository',
        ]))->withContext('App\\Controller\\LocalController::index()', $container);
    }
}
