<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalControllershowService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.wt..67W.App\Controller\LocalController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wt..67W.App\\Controller\\LocalController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'local' => ['privates', '.errored..service_locator.wt..67W.App\\Entity\\Local', NULL, 'Cannot autowire service ".service_locator.wt..67W": it needs an instance of "App\\Entity\\Local" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'local' => 'App\\Entity\\Local',
        ]))->withContext('App\\Controller\\LocalController::show()', $container);
    }
}
