<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\LocalType' shared autowired service.
     *
     * @return \App\Form\LocalType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\LocalType'] = new \App\Form\LocalType();
    }
}
