<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LocalRepository' shared autowired service.
     *
     * @return \App\Repository\LocalRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LocalRepository'] = new \App\Repository\LocalRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
