<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.8qx4UPg.App\Entity\Local' shared service.
     *
     * @return \App\Entity\Local
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8qx4UPg": it needs an instance of "App\\Entity\\Local" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
