<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalControllerdeleteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.8qx4UPg.App\Controller\LocalController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.8qx4UPg'] ?? $container->load('get_ServiceLocator_8qx4UPgService'));

        if (isset($container->privates['.service_locator.8qx4UPg.App\\Controller\\LocalController::delete()'])) {
            return $container->privates['.service_locator.8qx4UPg.App\\Controller\\LocalController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\LocalController::delete()', $container);

        if (isset($container->privates['.service_locator.8qx4UPg.App\\Controller\\LocalController::delete()'])) {
            return $container->privates['.service_locator.8qx4UPg.App\\Controller\\LocalController::delete()'];
        }

        return $container->privates['.service_locator.8qx4UPg.App\\Controller\\LocalController::delete()'] = $instance;
    }
}
