<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\LocalController' shared autowired service.
     *
     * @return \App\Controller\LocalController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\LocalController'] = $instance = new \App\Controller\LocalController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\LocalController', $container));

        return $instance;
    }
}
