<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.cXCrH8j.App\Controller\PrestationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cXCrH8j.App\\Controller\\PrestationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'prestationRepository' => ['privates', 'App\\Repository\\PrestationRepository', 'getPrestationRepositoryService', true],
        ], [
            'prestationRepository' => 'App\\Repository\\PrestationRepository',
        ]))->withContext('App\\Controller\\PrestationController::index()', $container);
    }
}
