<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationControllershowService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.7bEyMfQ.App\Controller\PrestationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7bEyMfQ.App\\Controller\\PrestationController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'prestation' => ['privates', '.errored..service_locator.7bEyMfQ.App\\Entity\\Prestation', NULL, 'Cannot autowire service ".service_locator.7bEyMfQ": it needs an instance of "App\\Entity\\Prestation" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'prestation' => 'App\\Entity\\Prestation',
        ]))->withContext('App\\Controller\\PrestationController::show()', $container);
    }
}
