<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.9.k60C..App\Controller\PrestationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.9.k60C.'] ?? $container->load('get_ServiceLocator_9_K60C_Service'));

        if (isset($container->privates['.service_locator.9.k60C..App\\Controller\\PrestationController::edit()'])) {
            return $container->privates['.service_locator.9.k60C..App\\Controller\\PrestationController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\PrestationController::edit()', $container);

        if (isset($container->privates['.service_locator.9.k60C..App\\Controller\\PrestationController::edit()'])) {
            return $container->privates['.service_locator.9.k60C..App\\Controller\\PrestationController::edit()'];
        }

        return $container->privates['.service_locator.9.k60C..App\\Controller\\PrestationController::edit()'] = $instance;
    }
}
