<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfGeneratorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\PdfGenerator' shared autowired service.
     *
     * @return \App\Service\PdfGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['App\\Service\\PdfGenerator'])) {
            return $container->privates['App\\Service\\PdfGenerator'];
        }

        $instance = new \App\Service\PdfGenerator($a, \dirname(__DIR__, 4));

        if (isset($container->privates['App\\Service\\PdfGenerator'])) {
            return $container->privates['App\\Service\\PdfGenerator'];
        }

        return $container->privates['App\\Service\\PdfGenerator'] = $instance;
    }
}
