<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestation2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.9.k60C..App\Entity\Prestation' shared service.
     *
     * @return \App\Entity\Prestation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9.k60C.": it needs an instance of "App\\Entity\\Prestation" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
