<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PrestationController' shared autowired service.
     *
     * @return \App\Controller\PrestationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PrestationController'] = $instance = new \App\Controller\PrestationController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\PrestationController', $container));

        return $instance;
    }
}
