<?php

namespace ContainerTNm2nPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PrestationType' shared autowired service.
     *
     * @return \App\Form\PrestationType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PrestationType'] = new \App\Form\PrestationType();
    }
}
