<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTNm2nPd\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTNm2nPd/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTNm2nPd.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTNm2nPd\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTNm2nPd\App_KernelProdContainer([
    'container.build_hash' => 'TNm2nPd',
    'container.build_id' => '63b72094',
    'container.build_time' => 1770079820,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTNm2nPd');
