<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prix extends \App\Entity\Prix implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date_creation' => [parent::class, 'date_creation', null, 16],
        "\0".parent::class."\0".'demande_devis' => [parent::class, 'demande_devis', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'montant_ht' => [parent::class, 'montant_ht', null, 16],
        "\0".parent::class."\0".'remise' => [parent::class, 'remise', null, 16],
        "\0".parent::class."\0".'total_ttc' => [parent::class, 'total_ttc', null, 16],
        "\0".parent::class."\0".'tva' => [parent::class, 'tva', null, 16],
        'date_creation' => [parent::class, 'date_creation', null, 16],
        'demande_devis' => [parent::class, 'demande_devis', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'montant_ht' => [parent::class, 'montant_ht', null, 16],
        'remise' => [parent::class, 'remise', null, 16],
        'total_ttc' => [parent::class, 'total_ttc', null, 16],
        'tva' => [parent::class, 'tva', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
