<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DemandeDevis extends \App\Entity\DemandeDevis implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'creneau_horaire' => [parent::class, 'creneau_horaire', null, 16],
        "\0".parent::class."\0".'date_creation' => [parent::class, 'date_creation', null, 16],
        "\0".parent::class."\0".'date_demande' => [parent::class, 'date_demande', null, 16],
        "\0".parent::class."\0".'demandePrestations' => [parent::class, 'demandePrestations', null, 16],
        "\0".parent::class."\0".'frequence' => [parent::class, 'frequence', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'local' => [parent::class, 'local', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'creneau_horaire' => [parent::class, 'creneau_horaire', null, 16],
        'date_creation' => [parent::class, 'date_creation', null, 16],
        'date_demande' => [parent::class, 'date_demande', null, 16],
        'demandePrestations' => [parent::class, 'demandePrestations', null, 16],
        'frequence' => [parent::class, 'frequence', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'local' => [parent::class, 'local', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
