<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Local extends \App\Entity\Local implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'demandeDevis' => [parent::class, 'demandeDevis', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'surface_m2' => [parent::class, 'surface_m2', null, 16],
        "\0".parent::class."\0".'type_local' => [parent::class, 'type_local', null, 16],
        "\0".parent::class."\0".'ville' => [parent::class, 'ville', null, 16],
        'demandeDevis' => [parent::class, 'demandeDevis', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'surface_m2' => [parent::class, 'surface_m2', null, 16],
        'type_local' => [parent::class, 'type_local', null, 16],
        'ville' => [parent::class, 'ville', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
