<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DemandePrestation extends \App\Entity\DemandePrestation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Demande_devis' => [parent::class, 'Demande_devis', null, 16],
        "\0".parent::class."\0".'admin_description' => [parent::class, 'admin_description', null, 16],
        "\0".parent::class."\0".'details_specifiques' => [parent::class, 'details_specifiques', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'prestation' => [parent::class, 'prestation', null, 16],
        'Demande_devis' => [parent::class, 'Demande_devis', null, 16],
        'admin_description' => [parent::class, 'admin_description', null, 16],
        'details_specifiques' => [parent::class, 'details_specifiques', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'prestation' => [parent::class, 'prestation', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
